---
title: "NOAA Visualization Package"
author: "Anh Dang"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This is `noaa.visualise` package, working with the NOAA Significant Earthquakes dataset 
to support the process of visualising and gaining information, including functions to: 

- Cleaning and filtering data
- Plot the significant earthquakes in NOAA datasets by timeline
- Plot the significant earthquakes in NOAA datasets by longitude and latitude

## Package Structure

The packages includes the below groups:
  
Group                 | Functions
----------------------| ----------------------------
Cleaning the raw data | eq_clean_data(), eq_location_clean(), eq_country_filter()
Visualisation tools   | geom_timeline(), geom_timeline_lable(), stat_timeline(), theme_timeline()
Mapping tools         | eq_map(), eq_create_label()

## Cleaning the raw data

To make the data appropriate to visualize by the tools provided in the package. You should clean the data.

## geom_timeline and geom_timeline_label

These geom are used altogether with the `gglot2`. You can choose the visualized timezone by `xmin` and `xmax` parameters. Mutiple information could be set by `size` and `color` (similar to other ggplot2 geoms).
`geom_timeline_label` would add the `LOCATION_NAME` to the timeline, the number of label would be assigned to `n_max` largest earthquakes.

## Visualize earthquakes in the map
The earthquakes could be visualized on the geographical maps, with specific pop-up information, with the `eq_map`. The `eq_create_label` could be used together to create more meaningful popup texts.

